server:
  port: 6787
spring:
  application:
    name: eureka-provider
eureka:
  instance:
    appname: eureka-provider
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true