server:
  port: 8080
spring:
  application:
    name: eureka-consumer
eureka:
  instance:
    prefer-ip-address: false
    appname: eureka-consumer
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
user:
  movieurl: http://eureka-provider

eureka-provider: #在服务消费者配置服务提供者的服务名
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule